// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/usezoracle/tapp/api/ent/merchantbankaccount"
	"github.com/usezoracle/tapp/api/ent/senderprofile"
)

// MerchantBankAccountCreate is the builder for creating a MerchantBankAccount entity.
type MerchantBankAccountCreate struct {
	config
	mutation *MerchantBankAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (mbac *MerchantBankAccountCreate) SetCreatedAt(t time.Time) *MerchantBankAccountCreate {
	mbac.mutation.SetCreatedAt(t)
	return mbac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mbac *MerchantBankAccountCreate) SetNillableCreatedAt(t *time.Time) *MerchantBankAccountCreate {
	if t != nil {
		mbac.SetCreatedAt(*t)
	}
	return mbac
}

// SetUpdatedAt sets the "updated_at" field.
func (mbac *MerchantBankAccountCreate) SetUpdatedAt(t time.Time) *MerchantBankAccountCreate {
	mbac.mutation.SetUpdatedAt(t)
	return mbac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mbac *MerchantBankAccountCreate) SetNillableUpdatedAt(t *time.Time) *MerchantBankAccountCreate {
	if t != nil {
		mbac.SetUpdatedAt(*t)
	}
	return mbac
}

// SetCurrency sets the "currency" field.
func (mbac *MerchantBankAccountCreate) SetCurrency(s string) *MerchantBankAccountCreate {
	mbac.mutation.SetCurrency(s)
	return mbac
}

// SetBankCode sets the "bank_code" field.
func (mbac *MerchantBankAccountCreate) SetBankCode(s string) *MerchantBankAccountCreate {
	mbac.mutation.SetBankCode(s)
	return mbac
}

// SetAccountNumber sets the "account_number" field.
func (mbac *MerchantBankAccountCreate) SetAccountNumber(s string) *MerchantBankAccountCreate {
	mbac.mutation.SetAccountNumber(s)
	return mbac
}

// SetAccountName sets the "account_name" field.
func (mbac *MerchantBankAccountCreate) SetAccountName(s string) *MerchantBankAccountCreate {
	mbac.mutation.SetAccountName(s)
	return mbac
}

// SetFintavaBankCode sets the "fintava_bank_code" field.
func (mbac *MerchantBankAccountCreate) SetFintavaBankCode(s string) *MerchantBankAccountCreate {
	mbac.mutation.SetFintavaBankCode(s)
	return mbac
}

// SetNillableFintavaBankCode sets the "fintava_bank_code" field if the given value is not nil.
func (mbac *MerchantBankAccountCreate) SetNillableFintavaBankCode(s *string) *MerchantBankAccountCreate {
	if s != nil {
		mbac.SetFintavaBankCode(*s)
	}
	return mbac
}

// SetVerifiedAt sets the "verified_at" field.
func (mbac *MerchantBankAccountCreate) SetVerifiedAt(t time.Time) *MerchantBankAccountCreate {
	mbac.mutation.SetVerifiedAt(t)
	return mbac
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (mbac *MerchantBankAccountCreate) SetNillableVerifiedAt(t *time.Time) *MerchantBankAccountCreate {
	if t != nil {
		mbac.SetVerifiedAt(*t)
	}
	return mbac
}

// SetID sets the "id" field.
func (mbac *MerchantBankAccountCreate) SetID(u uuid.UUID) *MerchantBankAccountCreate {
	mbac.mutation.SetID(u)
	return mbac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mbac *MerchantBankAccountCreate) SetNillableID(u *uuid.UUID) *MerchantBankAccountCreate {
	if u != nil {
		mbac.SetID(*u)
	}
	return mbac
}

// SetSenderProfileID sets the "sender_profile" edge to the SenderProfile entity by ID.
func (mbac *MerchantBankAccountCreate) SetSenderProfileID(id uuid.UUID) *MerchantBankAccountCreate {
	mbac.mutation.SetSenderProfileID(id)
	return mbac
}

// SetSenderProfile sets the "sender_profile" edge to the SenderProfile entity.
func (mbac *MerchantBankAccountCreate) SetSenderProfile(s *SenderProfile) *MerchantBankAccountCreate {
	return mbac.SetSenderProfileID(s.ID)
}

// Mutation returns the MerchantBankAccountMutation object of the builder.
func (mbac *MerchantBankAccountCreate) Mutation() *MerchantBankAccountMutation {
	return mbac.mutation
}

// Save creates the MerchantBankAccount in the database.
func (mbac *MerchantBankAccountCreate) Save(ctx context.Context) (*MerchantBankAccount, error) {
	mbac.defaults()
	return withHooks(ctx, mbac.sqlSave, mbac.mutation, mbac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mbac *MerchantBankAccountCreate) SaveX(ctx context.Context) *MerchantBankAccount {
	v, err := mbac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mbac *MerchantBankAccountCreate) Exec(ctx context.Context) error {
	_, err := mbac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mbac *MerchantBankAccountCreate) ExecX(ctx context.Context) {
	if err := mbac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mbac *MerchantBankAccountCreate) defaults() {
	if _, ok := mbac.mutation.CreatedAt(); !ok {
		v := merchantbankaccount.DefaultCreatedAt()
		mbac.mutation.SetCreatedAt(v)
	}
	if _, ok := mbac.mutation.UpdatedAt(); !ok {
		v := merchantbankaccount.DefaultUpdatedAt()
		mbac.mutation.SetUpdatedAt(v)
	}
	if _, ok := mbac.mutation.ID(); !ok {
		v := merchantbankaccount.DefaultID()
		mbac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mbac *MerchantBankAccountCreate) check() error {
	if _, ok := mbac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MerchantBankAccount.created_at"`)}
	}
	if _, ok := mbac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MerchantBankAccount.updated_at"`)}
	}
	if _, ok := mbac.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "MerchantBankAccount.currency"`)}
	}
	if v, ok := mbac.mutation.Currency(); ok {
		if err := merchantbankaccount.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "MerchantBankAccount.currency": %w`, err)}
		}
	}
	if _, ok := mbac.mutation.BankCode(); !ok {
		return &ValidationError{Name: "bank_code", err: errors.New(`ent: missing required field "MerchantBankAccount.bank_code"`)}
	}
	if v, ok := mbac.mutation.BankCode(); ok {
		if err := merchantbankaccount.BankCodeValidator(v); err != nil {
			return &ValidationError{Name: "bank_code", err: fmt.Errorf(`ent: validator failed for field "MerchantBankAccount.bank_code": %w`, err)}
		}
	}
	if _, ok := mbac.mutation.AccountNumber(); !ok {
		return &ValidationError{Name: "account_number", err: errors.New(`ent: missing required field "MerchantBankAccount.account_number"`)}
	}
	if v, ok := mbac.mutation.AccountNumber(); ok {
		if err := merchantbankaccount.AccountNumberValidator(v); err != nil {
			return &ValidationError{Name: "account_number", err: fmt.Errorf(`ent: validator failed for field "MerchantBankAccount.account_number": %w`, err)}
		}
	}
	if _, ok := mbac.mutation.AccountName(); !ok {
		return &ValidationError{Name: "account_name", err: errors.New(`ent: missing required field "MerchantBankAccount.account_name"`)}
	}
	if v, ok := mbac.mutation.AccountName(); ok {
		if err := merchantbankaccount.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "MerchantBankAccount.account_name": %w`, err)}
		}
	}
	if len(mbac.mutation.SenderProfileIDs()) == 0 {
		return &ValidationError{Name: "sender_profile", err: errors.New(`ent: missing required edge "MerchantBankAccount.sender_profile"`)}
	}
	return nil
}

func (mbac *MerchantBankAccountCreate) sqlSave(ctx context.Context) (*MerchantBankAccount, error) {
	if err := mbac.check(); err != nil {
		return nil, err
	}
	_node, _spec := mbac.createSpec()
	if err := sqlgraph.CreateNode(ctx, mbac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mbac.mutation.id = &_node.ID
	mbac.mutation.done = true
	return _node, nil
}

func (mbac *MerchantBankAccountCreate) createSpec() (*MerchantBankAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &MerchantBankAccount{config: mbac.config}
		_spec = sqlgraph.NewCreateSpec(merchantbankaccount.Table, sqlgraph.NewFieldSpec(merchantbankaccount.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = mbac.conflict
	if id, ok := mbac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mbac.mutation.CreatedAt(); ok {
		_spec.SetField(merchantbankaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mbac.mutation.UpdatedAt(); ok {
		_spec.SetField(merchantbankaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := mbac.mutation.Currency(); ok {
		_spec.SetField(merchantbankaccount.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := mbac.mutation.BankCode(); ok {
		_spec.SetField(merchantbankaccount.FieldBankCode, field.TypeString, value)
		_node.BankCode = value
	}
	if value, ok := mbac.mutation.AccountNumber(); ok {
		_spec.SetField(merchantbankaccount.FieldAccountNumber, field.TypeString, value)
		_node.AccountNumber = value
	}
	if value, ok := mbac.mutation.AccountName(); ok {
		_spec.SetField(merchantbankaccount.FieldAccountName, field.TypeString, value)
		_node.AccountName = value
	}
	if value, ok := mbac.mutation.FintavaBankCode(); ok {
		_spec.SetField(merchantbankaccount.FieldFintavaBankCode, field.TypeString, value)
		_node.FintavaBankCode = &value
	}
	if value, ok := mbac.mutation.VerifiedAt(); ok {
		_spec.SetField(merchantbankaccount.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if nodes := mbac.mutation.SenderProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   merchantbankaccount.SenderProfileTable,
			Columns: []string{merchantbankaccount.SenderProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(senderprofile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.sender_profile_merchant_bank_account = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MerchantBankAccount.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MerchantBankAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (mbac *MerchantBankAccountCreate) OnConflict(opts ...sql.ConflictOption) *MerchantBankAccountUpsertOne {
	mbac.conflict = opts
	return &MerchantBankAccountUpsertOne{
		create: mbac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MerchantBankAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mbac *MerchantBankAccountCreate) OnConflictColumns(columns ...string) *MerchantBankAccountUpsertOne {
	mbac.conflict = append(mbac.conflict, sql.ConflictColumns(columns...))
	return &MerchantBankAccountUpsertOne{
		create: mbac,
	}
}

type (
	// MerchantBankAccountUpsertOne is the builder for "upsert"-ing
	//  one MerchantBankAccount node.
	MerchantBankAccountUpsertOne struct {
		create *MerchantBankAccountCreate
	}

	// MerchantBankAccountUpsert is the "OnConflict" setter.
	MerchantBankAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MerchantBankAccountUpsert) SetUpdatedAt(v time.Time) *MerchantBankAccountUpsert {
	u.Set(merchantbankaccount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MerchantBankAccountUpsert) UpdateUpdatedAt() *MerchantBankAccountUpsert {
	u.SetExcluded(merchantbankaccount.FieldUpdatedAt)
	return u
}

// SetCurrency sets the "currency" field.
func (u *MerchantBankAccountUpsert) SetCurrency(v string) *MerchantBankAccountUpsert {
	u.Set(merchantbankaccount.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *MerchantBankAccountUpsert) UpdateCurrency() *MerchantBankAccountUpsert {
	u.SetExcluded(merchantbankaccount.FieldCurrency)
	return u
}

// SetBankCode sets the "bank_code" field.
func (u *MerchantBankAccountUpsert) SetBankCode(v string) *MerchantBankAccountUpsert {
	u.Set(merchantbankaccount.FieldBankCode, v)
	return u
}

// UpdateBankCode sets the "bank_code" field to the value that was provided on create.
func (u *MerchantBankAccountUpsert) UpdateBankCode() *MerchantBankAccountUpsert {
	u.SetExcluded(merchantbankaccount.FieldBankCode)
	return u
}

// SetAccountNumber sets the "account_number" field.
func (u *MerchantBankAccountUpsert) SetAccountNumber(v string) *MerchantBankAccountUpsert {
	u.Set(merchantbankaccount.FieldAccountNumber, v)
	return u
}

// UpdateAccountNumber sets the "account_number" field to the value that was provided on create.
func (u *MerchantBankAccountUpsert) UpdateAccountNumber() *MerchantBankAccountUpsert {
	u.SetExcluded(merchantbankaccount.FieldAccountNumber)
	return u
}

// SetAccountName sets the "account_name" field.
func (u *MerchantBankAccountUpsert) SetAccountName(v string) *MerchantBankAccountUpsert {
	u.Set(merchantbankaccount.FieldAccountName, v)
	return u
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *MerchantBankAccountUpsert) UpdateAccountName() *MerchantBankAccountUpsert {
	u.SetExcluded(merchantbankaccount.FieldAccountName)
	return u
}

// SetFintavaBankCode sets the "fintava_bank_code" field.
func (u *MerchantBankAccountUpsert) SetFintavaBankCode(v string) *MerchantBankAccountUpsert {
	u.Set(merchantbankaccount.FieldFintavaBankCode, v)
	return u
}

// UpdateFintavaBankCode sets the "fintava_bank_code" field to the value that was provided on create.
func (u *MerchantBankAccountUpsert) UpdateFintavaBankCode() *MerchantBankAccountUpsert {
	u.SetExcluded(merchantbankaccount.FieldFintavaBankCode)
	return u
}

// ClearFintavaBankCode clears the value of the "fintava_bank_code" field.
func (u *MerchantBankAccountUpsert) ClearFintavaBankCode() *MerchantBankAccountUpsert {
	u.SetNull(merchantbankaccount.FieldFintavaBankCode)
	return u
}

// SetVerifiedAt sets the "verified_at" field.
func (u *MerchantBankAccountUpsert) SetVerifiedAt(v time.Time) *MerchantBankAccountUpsert {
	u.Set(merchantbankaccount.FieldVerifiedAt, v)
	return u
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *MerchantBankAccountUpsert) UpdateVerifiedAt() *MerchantBankAccountUpsert {
	u.SetExcluded(merchantbankaccount.FieldVerifiedAt)
	return u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *MerchantBankAccountUpsert) ClearVerifiedAt() *MerchantBankAccountUpsert {
	u.SetNull(merchantbankaccount.FieldVerifiedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MerchantBankAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(merchantbankaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MerchantBankAccountUpsertOne) UpdateNewValues() *MerchantBankAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(merchantbankaccount.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(merchantbankaccount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MerchantBankAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MerchantBankAccountUpsertOne) Ignore() *MerchantBankAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MerchantBankAccountUpsertOne) DoNothing() *MerchantBankAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MerchantBankAccountCreate.OnConflict
// documentation for more info.
func (u *MerchantBankAccountUpsertOne) Update(set func(*MerchantBankAccountUpsert)) *MerchantBankAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MerchantBankAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MerchantBankAccountUpsertOne) SetUpdatedAt(v time.Time) *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertOne) UpdateUpdatedAt() *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCurrency sets the "currency" field.
func (u *MerchantBankAccountUpsertOne) SetCurrency(v string) *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertOne) UpdateCurrency() *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateCurrency()
	})
}

// SetBankCode sets the "bank_code" field.
func (u *MerchantBankAccountUpsertOne) SetBankCode(v string) *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetBankCode(v)
	})
}

// UpdateBankCode sets the "bank_code" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertOne) UpdateBankCode() *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateBankCode()
	})
}

// SetAccountNumber sets the "account_number" field.
func (u *MerchantBankAccountUpsertOne) SetAccountNumber(v string) *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetAccountNumber(v)
	})
}

// UpdateAccountNumber sets the "account_number" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertOne) UpdateAccountNumber() *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateAccountNumber()
	})
}

// SetAccountName sets the "account_name" field.
func (u *MerchantBankAccountUpsertOne) SetAccountName(v string) *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetAccountName(v)
	})
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertOne) UpdateAccountName() *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateAccountName()
	})
}

// SetFintavaBankCode sets the "fintava_bank_code" field.
func (u *MerchantBankAccountUpsertOne) SetFintavaBankCode(v string) *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetFintavaBankCode(v)
	})
}

// UpdateFintavaBankCode sets the "fintava_bank_code" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertOne) UpdateFintavaBankCode() *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateFintavaBankCode()
	})
}

// ClearFintavaBankCode clears the value of the "fintava_bank_code" field.
func (u *MerchantBankAccountUpsertOne) ClearFintavaBankCode() *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.ClearFintavaBankCode()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *MerchantBankAccountUpsertOne) SetVerifiedAt(v time.Time) *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertOne) UpdateVerifiedAt() *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *MerchantBankAccountUpsertOne) ClearVerifiedAt() *MerchantBankAccountUpsertOne {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.ClearVerifiedAt()
	})
}

// Exec executes the query.
func (u *MerchantBankAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MerchantBankAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MerchantBankAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MerchantBankAccountUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MerchantBankAccountUpsertOne.ID is not supported by MySQL driver. Use MerchantBankAccountUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MerchantBankAccountUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MerchantBankAccountCreateBulk is the builder for creating many MerchantBankAccount entities in bulk.
type MerchantBankAccountCreateBulk struct {
	config
	err      error
	builders []*MerchantBankAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the MerchantBankAccount entities in the database.
func (mbacb *MerchantBankAccountCreateBulk) Save(ctx context.Context) ([]*MerchantBankAccount, error) {
	if mbacb.err != nil {
		return nil, mbacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mbacb.builders))
	nodes := make([]*MerchantBankAccount, len(mbacb.builders))
	mutators := make([]Mutator, len(mbacb.builders))
	for i := range mbacb.builders {
		func(i int, root context.Context) {
			builder := mbacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MerchantBankAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mbacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mbacb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mbacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mbacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mbacb *MerchantBankAccountCreateBulk) SaveX(ctx context.Context) []*MerchantBankAccount {
	v, err := mbacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mbacb *MerchantBankAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := mbacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mbacb *MerchantBankAccountCreateBulk) ExecX(ctx context.Context) {
	if err := mbacb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MerchantBankAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MerchantBankAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (mbacb *MerchantBankAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *MerchantBankAccountUpsertBulk {
	mbacb.conflict = opts
	return &MerchantBankAccountUpsertBulk{
		create: mbacb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MerchantBankAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mbacb *MerchantBankAccountCreateBulk) OnConflictColumns(columns ...string) *MerchantBankAccountUpsertBulk {
	mbacb.conflict = append(mbacb.conflict, sql.ConflictColumns(columns...))
	return &MerchantBankAccountUpsertBulk{
		create: mbacb,
	}
}

// MerchantBankAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of MerchantBankAccount nodes.
type MerchantBankAccountUpsertBulk struct {
	create *MerchantBankAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MerchantBankAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(merchantbankaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MerchantBankAccountUpsertBulk) UpdateNewValues() *MerchantBankAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(merchantbankaccount.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(merchantbankaccount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MerchantBankAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MerchantBankAccountUpsertBulk) Ignore() *MerchantBankAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MerchantBankAccountUpsertBulk) DoNothing() *MerchantBankAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MerchantBankAccountCreateBulk.OnConflict
// documentation for more info.
func (u *MerchantBankAccountUpsertBulk) Update(set func(*MerchantBankAccountUpsert)) *MerchantBankAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MerchantBankAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MerchantBankAccountUpsertBulk) SetUpdatedAt(v time.Time) *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertBulk) UpdateUpdatedAt() *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCurrency sets the "currency" field.
func (u *MerchantBankAccountUpsertBulk) SetCurrency(v string) *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertBulk) UpdateCurrency() *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateCurrency()
	})
}

// SetBankCode sets the "bank_code" field.
func (u *MerchantBankAccountUpsertBulk) SetBankCode(v string) *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetBankCode(v)
	})
}

// UpdateBankCode sets the "bank_code" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertBulk) UpdateBankCode() *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateBankCode()
	})
}

// SetAccountNumber sets the "account_number" field.
func (u *MerchantBankAccountUpsertBulk) SetAccountNumber(v string) *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetAccountNumber(v)
	})
}

// UpdateAccountNumber sets the "account_number" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertBulk) UpdateAccountNumber() *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateAccountNumber()
	})
}

// SetAccountName sets the "account_name" field.
func (u *MerchantBankAccountUpsertBulk) SetAccountName(v string) *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetAccountName(v)
	})
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertBulk) UpdateAccountName() *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateAccountName()
	})
}

// SetFintavaBankCode sets the "fintava_bank_code" field.
func (u *MerchantBankAccountUpsertBulk) SetFintavaBankCode(v string) *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetFintavaBankCode(v)
	})
}

// UpdateFintavaBankCode sets the "fintava_bank_code" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertBulk) UpdateFintavaBankCode() *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateFintavaBankCode()
	})
}

// ClearFintavaBankCode clears the value of the "fintava_bank_code" field.
func (u *MerchantBankAccountUpsertBulk) ClearFintavaBankCode() *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.ClearFintavaBankCode()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *MerchantBankAccountUpsertBulk) SetVerifiedAt(v time.Time) *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *MerchantBankAccountUpsertBulk) UpdateVerifiedAt() *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *MerchantBankAccountUpsertBulk) ClearVerifiedAt() *MerchantBankAccountUpsertBulk {
	return u.Update(func(s *MerchantBankAccountUpsert) {
		s.ClearVerifiedAt()
	})
}

// Exec executes the query.
func (u *MerchantBankAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MerchantBankAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MerchantBankAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MerchantBankAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
