// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/usezoracle/tapp/api/ent/merchantbankaccount"
	"github.com/usezoracle/tapp/api/ent/senderprofile"
)

// MerchantBankAccount is the model entity for the MerchantBankAccount schema.
type MerchantBankAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// BankCode holds the value of the "bank_code" field.
	BankCode string `json:"bank_code,omitempty"`
	// AccountNumber holds the value of the "account_number" field.
	AccountNumber string `json:"account_number,omitempty"`
	// AccountName holds the value of the "account_name" field.
	AccountName string `json:"account_name,omitempty"`
	// FintavaBankCode holds the value of the "fintava_bank_code" field.
	FintavaBankCode *string `json:"fintava_bank_code,omitempty"`
	// VerifiedAt holds the value of the "verified_at" field.
	VerifiedAt *time.Time `json:"verified_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MerchantBankAccountQuery when eager-loading is set.
	Edges                                MerchantBankAccountEdges `json:"edges"`
	sender_profile_merchant_bank_account *uuid.UUID
	selectValues                         sql.SelectValues
}

// MerchantBankAccountEdges holds the relations/edges for other nodes in the graph.
type MerchantBankAccountEdges struct {
	// SenderProfile holds the value of the sender_profile edge.
	SenderProfile *SenderProfile `json:"sender_profile,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SenderProfileOrErr returns the SenderProfile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MerchantBankAccountEdges) SenderProfileOrErr() (*SenderProfile, error) {
	if e.SenderProfile != nil {
		return e.SenderProfile, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: senderprofile.Label}
	}
	return nil, &NotLoadedError{edge: "sender_profile"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MerchantBankAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case merchantbankaccount.FieldCurrency, merchantbankaccount.FieldBankCode, merchantbankaccount.FieldAccountNumber, merchantbankaccount.FieldAccountName, merchantbankaccount.FieldFintavaBankCode:
			values[i] = new(sql.NullString)
		case merchantbankaccount.FieldCreatedAt, merchantbankaccount.FieldUpdatedAt, merchantbankaccount.FieldVerifiedAt:
			values[i] = new(sql.NullTime)
		case merchantbankaccount.FieldID:
			values[i] = new(uuid.UUID)
		case merchantbankaccount.ForeignKeys[0]: // sender_profile_merchant_bank_account
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MerchantBankAccount fields.
func (mba *MerchantBankAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case merchantbankaccount.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				mba.ID = *value
			}
		case merchantbankaccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				mba.CreatedAt = value.Time
			}
		case merchantbankaccount.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				mba.UpdatedAt = value.Time
			}
		case merchantbankaccount.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				mba.Currency = value.String
			}
		case merchantbankaccount.FieldBankCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bank_code", values[i])
			} else if value.Valid {
				mba.BankCode = value.String
			}
		case merchantbankaccount.FieldAccountNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_number", values[i])
			} else if value.Valid {
				mba.AccountNumber = value.String
			}
		case merchantbankaccount.FieldAccountName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_name", values[i])
			} else if value.Valid {
				mba.AccountName = value.String
			}
		case merchantbankaccount.FieldFintavaBankCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fintava_bank_code", values[i])
			} else if value.Valid {
				mba.FintavaBankCode = new(string)
				*mba.FintavaBankCode = value.String
			}
		case merchantbankaccount.FieldVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field verified_at", values[i])
			} else if value.Valid {
				mba.VerifiedAt = new(time.Time)
				*mba.VerifiedAt = value.Time
			}
		case merchantbankaccount.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field sender_profile_merchant_bank_account", values[i])
			} else if value.Valid {
				mba.sender_profile_merchant_bank_account = new(uuid.UUID)
				*mba.sender_profile_merchant_bank_account = *value.S.(*uuid.UUID)
			}
		default:
			mba.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MerchantBankAccount.
// This includes values selected through modifiers, order, etc.
func (mba *MerchantBankAccount) Value(name string) (ent.Value, error) {
	return mba.selectValues.Get(name)
}

// QuerySenderProfile queries the "sender_profile" edge of the MerchantBankAccount entity.
func (mba *MerchantBankAccount) QuerySenderProfile() *SenderProfileQuery {
	return NewMerchantBankAccountClient(mba.config).QuerySenderProfile(mba)
}

// Update returns a builder for updating this MerchantBankAccount.
// Note that you need to call MerchantBankAccount.Unwrap() before calling this method if this MerchantBankAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (mba *MerchantBankAccount) Update() *MerchantBankAccountUpdateOne {
	return NewMerchantBankAccountClient(mba.config).UpdateOne(mba)
}

// Unwrap unwraps the MerchantBankAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mba *MerchantBankAccount) Unwrap() *MerchantBankAccount {
	_tx, ok := mba.config.driver.(*txDriver)
	if !ok {
		panic("ent: MerchantBankAccount is not a transactional entity")
	}
	mba.config.driver = _tx.drv
	return mba
}

// String implements the fmt.Stringer.
func (mba *MerchantBankAccount) String() string {
	var builder strings.Builder
	builder.WriteString("MerchantBankAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mba.ID))
	builder.WriteString("created_at=")
	builder.WriteString(mba.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(mba.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(mba.Currency)
	builder.WriteString(", ")
	builder.WriteString("bank_code=")
	builder.WriteString(mba.BankCode)
	builder.WriteString(", ")
	builder.WriteString("account_number=")
	builder.WriteString(mba.AccountNumber)
	builder.WriteString(", ")
	builder.WriteString("account_name=")
	builder.WriteString(mba.AccountName)
	builder.WriteString(", ")
	if v := mba.FintavaBankCode; v != nil {
		builder.WriteString("fintava_bank_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := mba.VerifiedAt; v != nil {
		builder.WriteString("verified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MerchantBankAccounts is a parsable slice of MerchantBankAccount.
type MerchantBankAccounts []*MerchantBankAccount
