// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/usezoracle/tapp/api/ent/merchantbankaccount"
	"github.com/usezoracle/tapp/api/ent/predicate"
)

// MerchantBankAccountUpdate is the builder for updating MerchantBankAccount entities.
type MerchantBankAccountUpdate struct {
	config
	hooks    []Hook
	mutation *MerchantBankAccountMutation
}

// Where appends a list predicates to the MerchantBankAccountUpdate builder.
func (mbau *MerchantBankAccountUpdate) Where(ps ...predicate.MerchantBankAccount) *MerchantBankAccountUpdate {
	mbau.mutation.Where(ps...)
	return mbau
}

// SetUpdatedAt sets the "updated_at" field.
func (mbau *MerchantBankAccountUpdate) SetUpdatedAt(t time.Time) *MerchantBankAccountUpdate {
	mbau.mutation.SetUpdatedAt(t)
	return mbau
}

// SetCurrency sets the "currency" field.
func (mbau *MerchantBankAccountUpdate) SetCurrency(s string) *MerchantBankAccountUpdate {
	mbau.mutation.SetCurrency(s)
	return mbau
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (mbau *MerchantBankAccountUpdate) SetNillableCurrency(s *string) *MerchantBankAccountUpdate {
	if s != nil {
		mbau.SetCurrency(*s)
	}
	return mbau
}

// SetBankCode sets the "bank_code" field.
func (mbau *MerchantBankAccountUpdate) SetBankCode(s string) *MerchantBankAccountUpdate {
	mbau.mutation.SetBankCode(s)
	return mbau
}

// SetNillableBankCode sets the "bank_code" field if the given value is not nil.
func (mbau *MerchantBankAccountUpdate) SetNillableBankCode(s *string) *MerchantBankAccountUpdate {
	if s != nil {
		mbau.SetBankCode(*s)
	}
	return mbau
}

// SetAccountNumber sets the "account_number" field.
func (mbau *MerchantBankAccountUpdate) SetAccountNumber(s string) *MerchantBankAccountUpdate {
	mbau.mutation.SetAccountNumber(s)
	return mbau
}

// SetNillableAccountNumber sets the "account_number" field if the given value is not nil.
func (mbau *MerchantBankAccountUpdate) SetNillableAccountNumber(s *string) *MerchantBankAccountUpdate {
	if s != nil {
		mbau.SetAccountNumber(*s)
	}
	return mbau
}

// SetAccountName sets the "account_name" field.
func (mbau *MerchantBankAccountUpdate) SetAccountName(s string) *MerchantBankAccountUpdate {
	mbau.mutation.SetAccountName(s)
	return mbau
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (mbau *MerchantBankAccountUpdate) SetNillableAccountName(s *string) *MerchantBankAccountUpdate {
	if s != nil {
		mbau.SetAccountName(*s)
	}
	return mbau
}

// SetFintavaBankCode sets the "fintava_bank_code" field.
func (mbau *MerchantBankAccountUpdate) SetFintavaBankCode(s string) *MerchantBankAccountUpdate {
	mbau.mutation.SetFintavaBankCode(s)
	return mbau
}

// SetNillableFintavaBankCode sets the "fintava_bank_code" field if the given value is not nil.
func (mbau *MerchantBankAccountUpdate) SetNillableFintavaBankCode(s *string) *MerchantBankAccountUpdate {
	if s != nil {
		mbau.SetFintavaBankCode(*s)
	}
	return mbau
}

// ClearFintavaBankCode clears the value of the "fintava_bank_code" field.
func (mbau *MerchantBankAccountUpdate) ClearFintavaBankCode() *MerchantBankAccountUpdate {
	mbau.mutation.ClearFintavaBankCode()
	return mbau
}

// SetVerifiedAt sets the "verified_at" field.
func (mbau *MerchantBankAccountUpdate) SetVerifiedAt(t time.Time) *MerchantBankAccountUpdate {
	mbau.mutation.SetVerifiedAt(t)
	return mbau
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (mbau *MerchantBankAccountUpdate) SetNillableVerifiedAt(t *time.Time) *MerchantBankAccountUpdate {
	if t != nil {
		mbau.SetVerifiedAt(*t)
	}
	return mbau
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (mbau *MerchantBankAccountUpdate) ClearVerifiedAt() *MerchantBankAccountUpdate {
	mbau.mutation.ClearVerifiedAt()
	return mbau
}

// Mutation returns the MerchantBankAccountMutation object of the builder.
func (mbau *MerchantBankAccountUpdate) Mutation() *MerchantBankAccountMutation {
	return mbau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mbau *MerchantBankAccountUpdate) Save(ctx context.Context) (int, error) {
	mbau.defaults()
	return withHooks(ctx, mbau.sqlSave, mbau.mutation, mbau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mbau *MerchantBankAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := mbau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mbau *MerchantBankAccountUpdate) Exec(ctx context.Context) error {
	_, err := mbau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mbau *MerchantBankAccountUpdate) ExecX(ctx context.Context) {
	if err := mbau.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mbau *MerchantBankAccountUpdate) defaults() {
	if _, ok := mbau.mutation.UpdatedAt(); !ok {
		v := merchantbankaccount.UpdateDefaultUpdatedAt()
		mbau.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mbau *MerchantBankAccountUpdate) check() error {
	if v, ok := mbau.mutation.Currency(); ok {
		if err := merchantbankaccount.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "MerchantBankAccount.currency": %w`, err)}
		}
	}
	if v, ok := mbau.mutation.BankCode(); ok {
		if err := merchantbankaccount.BankCodeValidator(v); err != nil {
			return &ValidationError{Name: "bank_code", err: fmt.Errorf(`ent: validator failed for field "MerchantBankAccount.bank_code": %w`, err)}
		}
	}
	if v, ok := mbau.mutation.AccountNumber(); ok {
		if err := merchantbankaccount.AccountNumberValidator(v); err != nil {
			return &ValidationError{Name: "account_number", err: fmt.Errorf(`ent: validator failed for field "MerchantBankAccount.account_number": %w`, err)}
		}
	}
	if v, ok := mbau.mutation.AccountName(); ok {
		if err := merchantbankaccount.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "MerchantBankAccount.account_name": %w`, err)}
		}
	}
	if mbau.mutation.SenderProfileCleared() && len(mbau.mutation.SenderProfileIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MerchantBankAccount.sender_profile"`)
	}
	return nil
}

func (mbau *MerchantBankAccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mbau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(merchantbankaccount.Table, merchantbankaccount.Columns, sqlgraph.NewFieldSpec(merchantbankaccount.FieldID, field.TypeUUID))
	if ps := mbau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mbau.mutation.UpdatedAt(); ok {
		_spec.SetField(merchantbankaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := mbau.mutation.Currency(); ok {
		_spec.SetField(merchantbankaccount.FieldCurrency, field.TypeString, value)
	}
	if value, ok := mbau.mutation.BankCode(); ok {
		_spec.SetField(merchantbankaccount.FieldBankCode, field.TypeString, value)
	}
	if value, ok := mbau.mutation.AccountNumber(); ok {
		_spec.SetField(merchantbankaccount.FieldAccountNumber, field.TypeString, value)
	}
	if value, ok := mbau.mutation.AccountName(); ok {
		_spec.SetField(merchantbankaccount.FieldAccountName, field.TypeString, value)
	}
	if value, ok := mbau.mutation.FintavaBankCode(); ok {
		_spec.SetField(merchantbankaccount.FieldFintavaBankCode, field.TypeString, value)
	}
	if mbau.mutation.FintavaBankCodeCleared() {
		_spec.ClearField(merchantbankaccount.FieldFintavaBankCode, field.TypeString)
	}
	if value, ok := mbau.mutation.VerifiedAt(); ok {
		_spec.SetField(merchantbankaccount.FieldVerifiedAt, field.TypeTime, value)
	}
	if mbau.mutation.VerifiedAtCleared() {
		_spec.ClearField(merchantbankaccount.FieldVerifiedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mbau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{merchantbankaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mbau.mutation.done = true
	return n, nil
}

// MerchantBankAccountUpdateOne is the builder for updating a single MerchantBankAccount entity.
type MerchantBankAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MerchantBankAccountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (mbauo *MerchantBankAccountUpdateOne) SetUpdatedAt(t time.Time) *MerchantBankAccountUpdateOne {
	mbauo.mutation.SetUpdatedAt(t)
	return mbauo
}

// SetCurrency sets the "currency" field.
func (mbauo *MerchantBankAccountUpdateOne) SetCurrency(s string) *MerchantBankAccountUpdateOne {
	mbauo.mutation.SetCurrency(s)
	return mbauo
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (mbauo *MerchantBankAccountUpdateOne) SetNillableCurrency(s *string) *MerchantBankAccountUpdateOne {
	if s != nil {
		mbauo.SetCurrency(*s)
	}
	return mbauo
}

// SetBankCode sets the "bank_code" field.
func (mbauo *MerchantBankAccountUpdateOne) SetBankCode(s string) *MerchantBankAccountUpdateOne {
	mbauo.mutation.SetBankCode(s)
	return mbauo
}

// SetNillableBankCode sets the "bank_code" field if the given value is not nil.
func (mbauo *MerchantBankAccountUpdateOne) SetNillableBankCode(s *string) *MerchantBankAccountUpdateOne {
	if s != nil {
		mbauo.SetBankCode(*s)
	}
	return mbauo
}

// SetAccountNumber sets the "account_number" field.
func (mbauo *MerchantBankAccountUpdateOne) SetAccountNumber(s string) *MerchantBankAccountUpdateOne {
	mbauo.mutation.SetAccountNumber(s)
	return mbauo
}

// SetNillableAccountNumber sets the "account_number" field if the given value is not nil.
func (mbauo *MerchantBankAccountUpdateOne) SetNillableAccountNumber(s *string) *MerchantBankAccountUpdateOne {
	if s != nil {
		mbauo.SetAccountNumber(*s)
	}
	return mbauo
}

// SetAccountName sets the "account_name" field.
func (mbauo *MerchantBankAccountUpdateOne) SetAccountName(s string) *MerchantBankAccountUpdateOne {
	mbauo.mutation.SetAccountName(s)
	return mbauo
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (mbauo *MerchantBankAccountUpdateOne) SetNillableAccountName(s *string) *MerchantBankAccountUpdateOne {
	if s != nil {
		mbauo.SetAccountName(*s)
	}
	return mbauo
}

// SetFintavaBankCode sets the "fintava_bank_code" field.
func (mbauo *MerchantBankAccountUpdateOne) SetFintavaBankCode(s string) *MerchantBankAccountUpdateOne {
	mbauo.mutation.SetFintavaBankCode(s)
	return mbauo
}

// SetNillableFintavaBankCode sets the "fintava_bank_code" field if the given value is not nil.
func (mbauo *MerchantBankAccountUpdateOne) SetNillableFintavaBankCode(s *string) *MerchantBankAccountUpdateOne {
	if s != nil {
		mbauo.SetFintavaBankCode(*s)
	}
	return mbauo
}

// ClearFintavaBankCode clears the value of the "fintava_bank_code" field.
func (mbauo *MerchantBankAccountUpdateOne) ClearFintavaBankCode() *MerchantBankAccountUpdateOne {
	mbauo.mutation.ClearFintavaBankCode()
	return mbauo
}

// SetVerifiedAt sets the "verified_at" field.
func (mbauo *MerchantBankAccountUpdateOne) SetVerifiedAt(t time.Time) *MerchantBankAccountUpdateOne {
	mbauo.mutation.SetVerifiedAt(t)
	return mbauo
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (mbauo *MerchantBankAccountUpdateOne) SetNillableVerifiedAt(t *time.Time) *MerchantBankAccountUpdateOne {
	if t != nil {
		mbauo.SetVerifiedAt(*t)
	}
	return mbauo
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (mbauo *MerchantBankAccountUpdateOne) ClearVerifiedAt() *MerchantBankAccountUpdateOne {
	mbauo.mutation.ClearVerifiedAt()
	return mbauo
}

// Mutation returns the MerchantBankAccountMutation object of the builder.
func (mbauo *MerchantBankAccountUpdateOne) Mutation() *MerchantBankAccountMutation {
	return mbauo.mutation
}

// Where appends a list predicates to the MerchantBankAccountUpdate builder.
func (mbauo *MerchantBankAccountUpdateOne) Where(ps ...predicate.MerchantBankAccount) *MerchantBankAccountUpdateOne {
	mbauo.mutation.Where(ps...)
	return mbauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mbauo *MerchantBankAccountUpdateOne) Select(field string, fields ...string) *MerchantBankAccountUpdateOne {
	mbauo.fields = append([]string{field}, fields...)
	return mbauo
}

// Save executes the query and returns the updated MerchantBankAccount entity.
func (mbauo *MerchantBankAccountUpdateOne) Save(ctx context.Context) (*MerchantBankAccount, error) {
	mbauo.defaults()
	return withHooks(ctx, mbauo.sqlSave, mbauo.mutation, mbauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mbauo *MerchantBankAccountUpdateOne) SaveX(ctx context.Context) *MerchantBankAccount {
	node, err := mbauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mbauo *MerchantBankAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := mbauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mbauo *MerchantBankAccountUpdateOne) ExecX(ctx context.Context) {
	if err := mbauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mbauo *MerchantBankAccountUpdateOne) defaults() {
	if _, ok := mbauo.mutation.UpdatedAt(); !ok {
		v := merchantbankaccount.UpdateDefaultUpdatedAt()
		mbauo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mbauo *MerchantBankAccountUpdateOne) check() error {
	if v, ok := mbauo.mutation.Currency(); ok {
		if err := merchantbankaccount.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "MerchantBankAccount.currency": %w`, err)}
		}
	}
	if v, ok := mbauo.mutation.BankCode(); ok {
		if err := merchantbankaccount.BankCodeValidator(v); err != nil {
			return &ValidationError{Name: "bank_code", err: fmt.Errorf(`ent: validator failed for field "MerchantBankAccount.bank_code": %w`, err)}
		}
	}
	if v, ok := mbauo.mutation.AccountNumber(); ok {
		if err := merchantbankaccount.AccountNumberValidator(v); err != nil {
			return &ValidationError{Name: "account_number", err: fmt.Errorf(`ent: validator failed for field "MerchantBankAccount.account_number": %w`, err)}
		}
	}
	if v, ok := mbauo.mutation.AccountName(); ok {
		if err := merchantbankaccount.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "MerchantBankAccount.account_name": %w`, err)}
		}
	}
	if mbauo.mutation.SenderProfileCleared() && len(mbauo.mutation.SenderProfileIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MerchantBankAccount.sender_profile"`)
	}
	return nil
}

func (mbauo *MerchantBankAccountUpdateOne) sqlSave(ctx context.Context) (_node *MerchantBankAccount, err error) {
	if err := mbauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(merchantbankaccount.Table, merchantbankaccount.Columns, sqlgraph.NewFieldSpec(merchantbankaccount.FieldID, field.TypeUUID))
	id, ok := mbauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MerchantBankAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mbauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, merchantbankaccount.FieldID)
		for _, f := range fields {
			if !merchantbankaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != merchantbankaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mbauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mbauo.mutation.UpdatedAt(); ok {
		_spec.SetField(merchantbankaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := mbauo.mutation.Currency(); ok {
		_spec.SetField(merchantbankaccount.FieldCurrency, field.TypeString, value)
	}
	if value, ok := mbauo.mutation.BankCode(); ok {
		_spec.SetField(merchantbankaccount.FieldBankCode, field.TypeString, value)
	}
	if value, ok := mbauo.mutation.AccountNumber(); ok {
		_spec.SetField(merchantbankaccount.FieldAccountNumber, field.TypeString, value)
	}
	if value, ok := mbauo.mutation.AccountName(); ok {
		_spec.SetField(merchantbankaccount.FieldAccountName, field.TypeString, value)
	}
	if value, ok := mbauo.mutation.FintavaBankCode(); ok {
		_spec.SetField(merchantbankaccount.FieldFintavaBankCode, field.TypeString, value)
	}
	if mbauo.mutation.FintavaBankCodeCleared() {
		_spec.ClearField(merchantbankaccount.FieldFintavaBankCode, field.TypeString)
	}
	if value, ok := mbauo.mutation.VerifiedAt(); ok {
		_spec.SetField(merchantbankaccount.FieldVerifiedAt, field.TypeTime, value)
	}
	if mbauo.mutation.VerifiedAtCleared() {
		_spec.ClearField(merchantbankaccount.FieldVerifiedAt, field.TypeTime)
	}
	_node = &MerchantBankAccount{config: mbauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mbauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{merchantbankaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mbauo.mutation.done = true
	return _node, nil
}
