// Code generated by ent, DO NOT EDIT.

package merchantbankaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/usezoracle/tapp/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldCurrency, v))
}

// BankCode applies equality check predicate on the "bank_code" field. It's identical to BankCodeEQ.
func BankCode(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldBankCode, v))
}

// AccountNumber applies equality check predicate on the "account_number" field. It's identical to AccountNumberEQ.
func AccountNumber(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldAccountNumber, v))
}

// AccountName applies equality check predicate on the "account_name" field. It's identical to AccountNameEQ.
func AccountName(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldAccountName, v))
}

// FintavaBankCode applies equality check predicate on the "fintava_bank_code" field. It's identical to FintavaBankCodeEQ.
func FintavaBankCode(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldFintavaBankCode, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldVerifiedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldContainsFold(FieldCurrency, v))
}

// BankCodeEQ applies the EQ predicate on the "bank_code" field.
func BankCodeEQ(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldBankCode, v))
}

// BankCodeNEQ applies the NEQ predicate on the "bank_code" field.
func BankCodeNEQ(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNEQ(FieldBankCode, v))
}

// BankCodeIn applies the In predicate on the "bank_code" field.
func BankCodeIn(vs ...string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldIn(FieldBankCode, vs...))
}

// BankCodeNotIn applies the NotIn predicate on the "bank_code" field.
func BankCodeNotIn(vs ...string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNotIn(FieldBankCode, vs...))
}

// BankCodeGT applies the GT predicate on the "bank_code" field.
func BankCodeGT(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGT(FieldBankCode, v))
}

// BankCodeGTE applies the GTE predicate on the "bank_code" field.
func BankCodeGTE(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGTE(FieldBankCode, v))
}

// BankCodeLT applies the LT predicate on the "bank_code" field.
func BankCodeLT(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLT(FieldBankCode, v))
}

// BankCodeLTE applies the LTE predicate on the "bank_code" field.
func BankCodeLTE(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLTE(FieldBankCode, v))
}

// BankCodeContains applies the Contains predicate on the "bank_code" field.
func BankCodeContains(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldContains(FieldBankCode, v))
}

// BankCodeHasPrefix applies the HasPrefix predicate on the "bank_code" field.
func BankCodeHasPrefix(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldHasPrefix(FieldBankCode, v))
}

// BankCodeHasSuffix applies the HasSuffix predicate on the "bank_code" field.
func BankCodeHasSuffix(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldHasSuffix(FieldBankCode, v))
}

// BankCodeEqualFold applies the EqualFold predicate on the "bank_code" field.
func BankCodeEqualFold(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEqualFold(FieldBankCode, v))
}

// BankCodeContainsFold applies the ContainsFold predicate on the "bank_code" field.
func BankCodeContainsFold(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldContainsFold(FieldBankCode, v))
}

// AccountNumberEQ applies the EQ predicate on the "account_number" field.
func AccountNumberEQ(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldAccountNumber, v))
}

// AccountNumberNEQ applies the NEQ predicate on the "account_number" field.
func AccountNumberNEQ(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNEQ(FieldAccountNumber, v))
}

// AccountNumberIn applies the In predicate on the "account_number" field.
func AccountNumberIn(vs ...string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldIn(FieldAccountNumber, vs...))
}

// AccountNumberNotIn applies the NotIn predicate on the "account_number" field.
func AccountNumberNotIn(vs ...string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNotIn(FieldAccountNumber, vs...))
}

// AccountNumberGT applies the GT predicate on the "account_number" field.
func AccountNumberGT(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGT(FieldAccountNumber, v))
}

// AccountNumberGTE applies the GTE predicate on the "account_number" field.
func AccountNumberGTE(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGTE(FieldAccountNumber, v))
}

// AccountNumberLT applies the LT predicate on the "account_number" field.
func AccountNumberLT(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLT(FieldAccountNumber, v))
}

// AccountNumberLTE applies the LTE predicate on the "account_number" field.
func AccountNumberLTE(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLTE(FieldAccountNumber, v))
}

// AccountNumberContains applies the Contains predicate on the "account_number" field.
func AccountNumberContains(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldContains(FieldAccountNumber, v))
}

// AccountNumberHasPrefix applies the HasPrefix predicate on the "account_number" field.
func AccountNumberHasPrefix(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldHasPrefix(FieldAccountNumber, v))
}

// AccountNumberHasSuffix applies the HasSuffix predicate on the "account_number" field.
func AccountNumberHasSuffix(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldHasSuffix(FieldAccountNumber, v))
}

// AccountNumberEqualFold applies the EqualFold predicate on the "account_number" field.
func AccountNumberEqualFold(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEqualFold(FieldAccountNumber, v))
}

// AccountNumberContainsFold applies the ContainsFold predicate on the "account_number" field.
func AccountNumberContainsFold(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldContainsFold(FieldAccountNumber, v))
}

// AccountNameEQ applies the EQ predicate on the "account_name" field.
func AccountNameEQ(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldAccountName, v))
}

// AccountNameNEQ applies the NEQ predicate on the "account_name" field.
func AccountNameNEQ(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNEQ(FieldAccountName, v))
}

// AccountNameIn applies the In predicate on the "account_name" field.
func AccountNameIn(vs ...string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldIn(FieldAccountName, vs...))
}

// AccountNameNotIn applies the NotIn predicate on the "account_name" field.
func AccountNameNotIn(vs ...string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNotIn(FieldAccountName, vs...))
}

// AccountNameGT applies the GT predicate on the "account_name" field.
func AccountNameGT(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGT(FieldAccountName, v))
}

// AccountNameGTE applies the GTE predicate on the "account_name" field.
func AccountNameGTE(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGTE(FieldAccountName, v))
}

// AccountNameLT applies the LT predicate on the "account_name" field.
func AccountNameLT(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLT(FieldAccountName, v))
}

// AccountNameLTE applies the LTE predicate on the "account_name" field.
func AccountNameLTE(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLTE(FieldAccountName, v))
}

// AccountNameContains applies the Contains predicate on the "account_name" field.
func AccountNameContains(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldContains(FieldAccountName, v))
}

// AccountNameHasPrefix applies the HasPrefix predicate on the "account_name" field.
func AccountNameHasPrefix(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldHasPrefix(FieldAccountName, v))
}

// AccountNameHasSuffix applies the HasSuffix predicate on the "account_name" field.
func AccountNameHasSuffix(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldHasSuffix(FieldAccountName, v))
}

// AccountNameEqualFold applies the EqualFold predicate on the "account_name" field.
func AccountNameEqualFold(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEqualFold(FieldAccountName, v))
}

// AccountNameContainsFold applies the ContainsFold predicate on the "account_name" field.
func AccountNameContainsFold(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldContainsFold(FieldAccountName, v))
}

// FintavaBankCodeEQ applies the EQ predicate on the "fintava_bank_code" field.
func FintavaBankCodeEQ(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldFintavaBankCode, v))
}

// FintavaBankCodeNEQ applies the NEQ predicate on the "fintava_bank_code" field.
func FintavaBankCodeNEQ(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNEQ(FieldFintavaBankCode, v))
}

// FintavaBankCodeIn applies the In predicate on the "fintava_bank_code" field.
func FintavaBankCodeIn(vs ...string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldIn(FieldFintavaBankCode, vs...))
}

// FintavaBankCodeNotIn applies the NotIn predicate on the "fintava_bank_code" field.
func FintavaBankCodeNotIn(vs ...string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNotIn(FieldFintavaBankCode, vs...))
}

// FintavaBankCodeGT applies the GT predicate on the "fintava_bank_code" field.
func FintavaBankCodeGT(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGT(FieldFintavaBankCode, v))
}

// FintavaBankCodeGTE applies the GTE predicate on the "fintava_bank_code" field.
func FintavaBankCodeGTE(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGTE(FieldFintavaBankCode, v))
}

// FintavaBankCodeLT applies the LT predicate on the "fintava_bank_code" field.
func FintavaBankCodeLT(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLT(FieldFintavaBankCode, v))
}

// FintavaBankCodeLTE applies the LTE predicate on the "fintava_bank_code" field.
func FintavaBankCodeLTE(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLTE(FieldFintavaBankCode, v))
}

// FintavaBankCodeContains applies the Contains predicate on the "fintava_bank_code" field.
func FintavaBankCodeContains(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldContains(FieldFintavaBankCode, v))
}

// FintavaBankCodeHasPrefix applies the HasPrefix predicate on the "fintava_bank_code" field.
func FintavaBankCodeHasPrefix(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldHasPrefix(FieldFintavaBankCode, v))
}

// FintavaBankCodeHasSuffix applies the HasSuffix predicate on the "fintava_bank_code" field.
func FintavaBankCodeHasSuffix(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldHasSuffix(FieldFintavaBankCode, v))
}

// FintavaBankCodeIsNil applies the IsNil predicate on the "fintava_bank_code" field.
func FintavaBankCodeIsNil() predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldIsNull(FieldFintavaBankCode))
}

// FintavaBankCodeNotNil applies the NotNil predicate on the "fintava_bank_code" field.
func FintavaBankCodeNotNil() predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNotNull(FieldFintavaBankCode))
}

// FintavaBankCodeEqualFold applies the EqualFold predicate on the "fintava_bank_code" field.
func FintavaBankCodeEqualFold(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEqualFold(FieldFintavaBankCode, v))
}

// FintavaBankCodeContainsFold applies the ContainsFold predicate on the "fintava_bank_code" field.
func FintavaBankCodeContainsFold(v string) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldContainsFold(FieldFintavaBankCode, v))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.FieldNotNull(FieldVerifiedAt))
}

// HasSenderProfile applies the HasEdge predicate on the "sender_profile" edge.
func HasSenderProfile() predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, SenderProfileTable, SenderProfileColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSenderProfileWith applies the HasEdge predicate on the "sender_profile" edge with a given conditions (other predicates).
func HasSenderProfileWith(preds ...predicate.SenderProfile) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(func(s *sql.Selector) {
		step := newSenderProfileStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MerchantBankAccount) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MerchantBankAccount) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MerchantBankAccount) predicate.MerchantBankAccount {
	return predicate.MerchantBankAccount(sql.NotPredicates(p))
}
